### ISSUE TITLE
Add cpu, memory and disk-info to the export

### ISSUE THREAD

**Issue by Crokoking** [infinityworks/prometheus-rancher-exporter#19]
The v2-beta API provides host-details that would be very useful to export:
- memoryInfo
- diskInfo
- cpuInfo
- osInfo

This would provide some of the data previously available via cadvisor-proxy.

**Comment by mytototo** [comment]
Any news about adding those info in the exporter?

**Comment by Rucknar** [comment]
Interesting one this, the fields mentioned above would replace some of the metrics of the node_exporter, not cadvisor though. 

With that in mind, the node exporter currently exports close to 600 metrics, i'm not sure there is yet enough information exposed in the API to make it a complete solution.

**Comment by Rucknar** [comment]
Going to hold off on this one, those fields vary depending on Rancher version and there are still some obvious gaps in the metrics for them to be useful. Open to PR's but i don't think it's a good source for this type of stat.
