### ISSUE TITLE
wrong state in case Stack is deleted or renamed

### ISSUE THREAD

**Issue by ferhimedamine** [infinityworks/prometheus-rancher-exporter#23]
Hello 

First, thanks a lot for the great work you did 👍 
Testing exporter using Prometheus and Grafana.. i do notice that when a stack is deleted or renamed, the rancher metrics for Stack state and service state does not get updated..
And that means in Grafana we keep seeing a stack that is supposed to be decommissioned already / or in case renamed i will end up having a duplicate.

I am using the latest version of the exporter.
Also using Rancher 1.6.0

Regards
Amine

**Comment by Rucknar** [comment]
Thanks for the ticket, good catch!

Somewhat busy over the next few days, I'll have a proper look at this later this week.

**Comment by Rucknar** [comment]
@ferhimedamine Does the state disappear after 5 minutes? I've checked the code and we don't store anything to the exporter. I suspect this is prometheus holding the metric for a period, usually 5 minutes. Can you confirm? Happy to re-open if that's not the case.
