### ISSUE TITLE
Log level ignored

### ISSUE THREAD

**Issue by maxwo** [infinityworks/prometheus-rancher-exporter#34]
It appears setting any value in the LOG_LEVEL environment variable leads to INFO level. I tried WARN, Warning, WARNING with no success. Any hint?
Thank you.

**Comment by Rucknar** [comment]
Give `latest` or `v0.22.88` a go, should be fixed!

**Comment by maxwo** [comment]
Thanks! Gonna check this on Monday. Keep your great work!
