### ISSUE TITLE
How to filter by Environment

### ISSUE THREAD

**Issue by phlegx** [infinityworks/prometheus-rancher-exporter#37]
First of all, thanks for the great work!

My question with Grafana: Is there a possibility to filter for example stacks and services by environment? If not, could we maybe add a flag so we can do a filter/regex for it?

**Comment by iamtgray** [comment]
Hi @phlegx - To answer your really old question, the quick answer is no. 

The long answer is: yes! ..but not with the rancher exporter directly. However you could use Prometheus recording rules (https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/), to add different and new labels for each environment, and then break down the environments in your grafana :)

Hope that helps

**Comment by iamtgray** [comment]
Duplicates #2
