### ISSUE TITLE
etcd incorrect health state

### ISSUE THREAD

**Issue by hiscal2015** [infinityworks/prometheus-rancher-exporter#40]
Hi,

In my kubernetes environment, all service health status looks fine except etcd, look at below metrics, 
why both of them return 0? Thanks.
rancher_service_health_status{health_state="healthy",name="etcd",stack_name="kubernetes"} 0
rancher_service_health_status{health_state="unhealthy",name="etcd",stack_name="kubernetes"} 0

![etcd](https://user-images.githubusercontent.com/15604715/34088143-629b562e-e3e2-11e7-8fb6-997c08e82fd1.jpg)

**Comment by Rucknar** [comment]
Just pushed a new version to `latest` and `v0.22.93`. Should resolve the issue, rancher added additional states to the health_status endpoint.
