### ISSUE TITLE
Failed to obtain stack_name for ipsec/cni-driver from the API

### ISSUE THREAD

**Issue by hiscal2015** [infinityworks/prometheus-rancher-exporter#41]
FYI.

Rancher version 1.6.10.
rancher exporter latest.

12/18/2017 8:07:02 PMWARN[26004] Failed to obtain stack_name for ipsec from the API
12/18/2017 8:07:02 PMWARN[26004] Failed to obtain stack_name for cni-driver from the API

**Comment by rudolftraunmueller-celum** [comment]
We face the same issue.

Rancher version v1.6.14
Rancher exporter infinityworks/prometheus-rancher-exporter:v0.22.52

5/22/2018 2:05:33 PMWARN[0589] Failed to obtain stack_name for rabbitmq from the API
5/22/2018 2:05:33 PMWARN[0589] Failed to obtain stack_name for keycloak from the API
5/22/2018 2:05:33 PMWARN[0589] Failed to obtain stack_name for graylog-elasticsearch from the API
