### ISSUE TITLE
rancher_service_health_status cannot get states from all hosts

### ISSUE THREAD

**Issue by reshmaUnni** [infinityworks/prometheus-rancher-exporter#44]
Hi,

I have prometheus-rancher-exporter:instance running as infrastructure stack on Rancher. I am trying to find the health status of a service deployed in Rancher
hellow-world stack has 4 instances of an application running under it. Two instances are running on server108, another one in server109 and another one on server110.

when I execute the below query:
**rancher_service_health_status{name="hello-world", env="prod"}**

**I get the below results**
rancher_service_health_status{env="prod",health_state="healthy",instance="server108.com:9173",job="prod_prometheus-rancher-exporter",name="hello-world4-5-3",stack_name="hello-world"}	1
rancher_service_health_status{env="prod",health_state="unhealthy",instance="server108.com:9173",job="prod_prometheus-rancher-exporter",name="hello-world4-5-3",stack_name="hello-world"}	0

I am not getting right count of instances and and also from every servers it is deployed. Is this a bug? Or is my query not right?

**Comment by Rucknar** [comment]
Hello, 

I believe this was recently fixed. Rancher added new health states to their API, we simply didn't capture them. Give `v0.22.94` a shot, if it's not working feel free to re-open.
